version: '2.4'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - bridge-net
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./assets:/usr/share/nginx/html/assets
      - ./index.html:/usr/share/nginx/html/index.html
      - nginx_logs:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RUNNING_IN_DOCKER=true
    env_file:
      - .env
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--loop",
        "asyncio"
      ]
    volumes:
      - ./app:/workspace/code/app
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - bridge-net
    depends_on:
      - redis
      - db
      - pgvector-db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nurses_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bridge-net

  pgvector-db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector_db
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - bridge-net

  worker:
    build: .
    command: celery -A app.worker.celery_app worker --concurrency=1 --loglevel=info
    volumes:
      - ./app:/workspace/code/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - bridge-net
    depends_on:
      - web
      - redis

  redis:
    image: redis:7
    networks:
      - bridge-net

  dashboard:
    build: .
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5557:5555
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - bridge-net
    depends_on:
      - web
      - redis
      - worker

volumes:
  local-vol:
    driver: local
  postgres_data:
  pgvector_data:
  nginx_logs:


networks:
  bridge-net:
    driver: bridge
