version: '3.8'

services:

  web:
    build: .
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --loop asyncio
    volumes:
      - ./app:/workspace/code/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.worker.celery_app worker --concurrency=1 --loglevel=info
    volumes:
      - ./app:/workspace/code/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7

  dashboard:
    build: .
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5557:5555
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
