version: '2.4'

services:
  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --loop asyncio
    volumes:
      - ./app:/workspace/code/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - bridge-net
    depends_on:
      - redis
      - db
      - ollama

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nurses_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bridge-net

  ollama:
    build: ./docker/ollama
    ports:
      - "11434:11434"
    volumes:
      - local-vol:/ollama
    networks:
      - bridge-net
    entrypoint: [ '/usr/bin/bash', 'pull-llm.sh' ]
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    pull_policy: always
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  worker:
    build: .
    command: celery -A app.worker.celery_app worker --concurrency=1 --loglevel=info
    volumes:
      - ./app:/workspace/code/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - bridge-net
    depends_on:
      - web
      - redis

  redis:
    image: redis:7
    networks:
      - bridge-net

  dashboard:
    build: .
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5557:5555
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - bridge-net
    depends_on:
      - web
      - redis
      - worker

volumes:
  local-vol:
    driver: local
  postgres_data:


networks:
  bridge-net:
    driver: bridge
